# Generated by Django 5.2.4 on 2025-07-28 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('special', 'Special')], max_length=50)),
                ('requirement', models.IntegerField()),
                ('experience_reward', models.IntegerField()),
                ('coin_reward', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'quests',
            },
        ),
        migrations.CreateModel(
            name='TeaCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rarity', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=500)),
                ('strength', models.IntegerField()),
                ('freshness', models.IntegerField()),
                ('aroma', models.IntegerField()),
                ('abilities', models.JSONField(default=list)),
                ('brewing_time', models.CharField(max_length=50)),
                ('brewing_temperature', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tea_cards',
            },
        ),
        migrations.CreateModel(
            name='WeeklyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('day_of_week', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('reward_type', models.CharField(max_length=50)),
                ('reward_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'weekly_events',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('requirement', models.IntegerField()),
                ('progress', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('experience_reward', models.IntegerField()),
                ('coin_reward', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('tea_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.teacard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
            options={
                'db_table': 'user_cards',
                'unique_together': {('user', 'tea_card')},
            },
        ),
    ]
